require 'fileutils'
require 'rails'
require 'pdf/report/generator/version'
require  File.dirname(__FILE__) + '/generator/wicked_core'
require  File.dirname(__FILE__) + '/generator/cdisc_changes_report'